// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGithubComGalptCakeStatsPkgTypes(in *jlexer.Lexer, out *StatsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "interfaces":
			if in.IsNull() {
				in.Skip()
				out.Interfaces = nil
			} else {
				in.Delim('[')
				if out.Interfaces == nil {
					if !in.IsDelim(']') {
						out.Interfaces = make([]CakeStats, 0, 0)
					} else {
						out.Interfaces = []CakeStats{}
					}
				} else {
					out.Interfaces = (out.Interfaces)[:0]
				}
				for !in.IsDelim(']') {
					var v1 CakeStats
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Interfaces = append(out.Interfaces, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UpdatedAt = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGalptCakeStatsPkgTypes(out *jwriter.Writer, in StatsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"interfaces\":"
		out.RawString(prefix[1:])
		if in.Interfaces == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Interfaces {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.String(string(in.UpdatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGalptCakeStatsPkgTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGalptCakeStatsPkgTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGalptCakeStatsPkgTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGalptCakeStatsPkgTypes(l, v)
}
func easyjson6601e8cdDecodeGithubComGalptCakeStatsPkgTypes1(in *jlexer.Lexer, out *HistorySample) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "t":
			if in.IsNull() {
				in.Skip()
			} else {
				out.T = int64(in.Int64())
			}
		case "tx":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Tx = float64(in.Float64())
			}
		case "av":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Av = float64(in.Float64())
			}
		case "pk":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Pk = float64(in.Float64())
			}
		case "dr":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Dr = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGalptCakeStatsPkgTypes1(out *jwriter.Writer, in HistorySample) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"t\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.T))
	}
	{
		const prefix string = ",\"tx\":"
		out.RawString(prefix)
		out.Float64(float64(in.Tx))
	}
	{
		const prefix string = ",\"av\":"
		out.RawString(prefix)
		out.Float64(float64(in.Av))
	}
	{
		const prefix string = ",\"pk\":"
		out.RawString(prefix)
		out.Float64(float64(in.Pk))
	}
	{
		const prefix string = ",\"dr\":"
		out.RawString(prefix)
		out.Float64(float64(in.Dr))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HistorySample) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGalptCakeStatsPkgTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HistorySample) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGalptCakeStatsPkgTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HistorySample) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGalptCakeStatsPkgTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HistorySample) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGalptCakeStatsPkgTypes1(l, v)
}
func easyjson6601e8cdDecodeGithubComGalptCakeStatsPkgTypes2(in *jlexer.Lexer, out *CakeTier) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "thresh":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Thresh = string(in.String())
			}
		case "target":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Target = string(in.String())
			}
		case "interval":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Interval = string(in.String())
			}
		case "pk_delay":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PkDelay = string(in.String())
			}
		case "av_delay":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvDelay = string(in.String())
			}
		case "sp_delay":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SpDelay = string(in.String())
			}
		case "backlog":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Backlog = string(in.String())
			}
		case "pkts":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Pkts = uint64(in.Uint64())
			}
		case "bytes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Bytes = uint64(in.Uint64())
			}
		case "way_inds":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WayInds = uint64(in.Uint64())
			}
		case "way_miss":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WayMiss = uint64(in.Uint64())
			}
		case "way_cols":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WayCols = uint64(in.Uint64())
			}
		case "drops":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Drops = uint64(in.Uint64())
			}
		case "marks":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Marks = uint64(in.Uint64())
			}
		case "ack_drop":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AckDrop = uint64(in.Uint64())
			}
		case "sp_flows":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SpFlows = uint64(in.Uint64())
			}
		case "bk_flows":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BkFlows = uint64(in.Uint64())
			}
		case "un_flows":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UnFlows = uint64(in.Uint64())
			}
		case "max_len":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxLen = uint64(in.Uint64())
			}
		case "quantum":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Quantum = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGalptCakeStatsPkgTypes2(out *jwriter.Writer, in CakeTier) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"thresh\":"
		out.RawString(prefix)
		out.String(string(in.Thresh))
	}
	{
		const prefix string = ",\"target\":"
		out.RawString(prefix)
		out.String(string(in.Target))
	}
	{
		const prefix string = ",\"interval\":"
		out.RawString(prefix)
		out.String(string(in.Interval))
	}
	{
		const prefix string = ",\"pk_delay\":"
		out.RawString(prefix)
		out.String(string(in.PkDelay))
	}
	{
		const prefix string = ",\"av_delay\":"
		out.RawString(prefix)
		out.String(string(in.AvDelay))
	}
	{
		const prefix string = ",\"sp_delay\":"
		out.RawString(prefix)
		out.String(string(in.SpDelay))
	}
	{
		const prefix string = ",\"backlog\":"
		out.RawString(prefix)
		out.String(string(in.Backlog))
	}
	{
		const prefix string = ",\"pkts\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Pkts))
	}
	{
		const prefix string = ",\"bytes\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Bytes))
	}
	{
		const prefix string = ",\"way_inds\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.WayInds))
	}
	{
		const prefix string = ",\"way_miss\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.WayMiss))
	}
	{
		const prefix string = ",\"way_cols\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.WayCols))
	}
	{
		const prefix string = ",\"drops\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Drops))
	}
	{
		const prefix string = ",\"marks\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Marks))
	}
	{
		const prefix string = ",\"ack_drop\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.AckDrop))
	}
	{
		const prefix string = ",\"sp_flows\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.SpFlows))
	}
	{
		const prefix string = ",\"bk_flows\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.BkFlows))
	}
	{
		const prefix string = ",\"un_flows\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.UnFlows))
	}
	{
		const prefix string = ",\"max_len\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.MaxLen))
	}
	{
		const prefix string = ",\"quantum\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Quantum))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CakeTier) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGalptCakeStatsPkgTypes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CakeTier) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGalptCakeStatsPkgTypes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CakeTier) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGalptCakeStatsPkgTypes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CakeTier) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGalptCakeStatsPkgTypes2(l, v)
}
func easyjson6601e8cdDecodeGithubComGalptCakeStatsPkgTypes3(in *jlexer.Lexer, out *CakeStats) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "interface":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Interface = string(in.String())
			}
		case "handle":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Handle = string(in.String())
			}
		case "direction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Direction = string(in.String())
			}
		case "bandwidth":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Bandwidth = string(in.String())
			}
		case "diffserv_mode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DiffservMode = string(in.String())
			}
		case "rtt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RTT = string(in.String())
			}
		case "overhead":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Overhead = string(in.String())
			}
		case "dual_mode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DualMode = string(in.String())
			}
		case "fwmark_mask":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FwmarkMask = string(in.String())
			}
		case "nat_enabled":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NATEnabled = bool(in.Bool())
			}
		case "atm_mode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ATMMode = string(in.String())
			}
		case "mpu":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MPU = string(in.String())
			}
		case "wash_enabled":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WashEnabled = bool(in.Bool())
			}
		case "memlimit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MemLimit = string(in.String())
			}
		case "raw_header":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawHeader = string(in.String())
			}
		case "sent_bytes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SentBytes = uint64(in.Uint64())
			}
		case "sent_pkts":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SentPkts = uint64(in.Uint64())
			}
		case "dropped":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Dropped = uint64(in.Uint64())
			}
		case "overlimits":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Overlimits = uint64(in.Uint64())
			}
		case "requeues":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Requeues = uint64(in.Uint64())
			}
		case "backlog_bytes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BacklogBytes = string(in.String())
			}
		case "backlog_pkts":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BacklogPkts = uint64(in.Uint64())
			}
		case "memory_used":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MemoryUsed = string(in.String())
			}
		case "memory_total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MemoryTotal = string(in.String())
			}
		case "capacity_estimate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CapacityEst = string(in.String())
			}
		case "min_net_size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinNetSize = string(in.String())
			}
		case "max_net_size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxNetSize = string(in.String())
			}
		case "min_adj_size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinAdjSize = string(in.String())
			}
		case "max_adj_size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxAdjSize = string(in.String())
			}
		case "avg_hdr_offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvgHdrOffset = string(in.String())
			}
		case "tiers":
			if in.IsNull() {
				in.Skip()
				out.Tiers = nil
			} else {
				in.Delim('[')
				if out.Tiers == nil {
					if !in.IsDelim(']') {
						out.Tiers = make([]CakeTier, 0, 0)
					} else {
						out.Tiers = []CakeTier{}
					}
				} else {
					out.Tiers = (out.Tiers)[:0]
				}
				for !in.IsDelim(']') {
					var v4 CakeTier
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Tiers = append(out.Tiers, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		case "tx_bytes_per_s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxBytesPerS = float64(in.Float64())
			}
		case "drops_per_s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DropsPerS = float64(in.Float64())
			}
		case "max_av_delay_ms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxAvDelayMs = float64(in.Float64())
			}
		case "max_pk_delay_ms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxPkDelayMs = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGalptCakeStatsPkgTypes3(out *jwriter.Writer, in CakeStats) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"interface\":"
		out.RawString(prefix[1:])
		out.String(string(in.Interface))
	}
	{
		const prefix string = ",\"handle\":"
		out.RawString(prefix)
		out.String(string(in.Handle))
	}
	{
		const prefix string = ",\"direction\":"
		out.RawString(prefix)
		out.String(string(in.Direction))
	}
	{
		const prefix string = ",\"bandwidth\":"
		out.RawString(prefix)
		out.String(string(in.Bandwidth))
	}
	{
		const prefix string = ",\"diffserv_mode\":"
		out.RawString(prefix)
		out.String(string(in.DiffservMode))
	}
	{
		const prefix string = ",\"rtt\":"
		out.RawString(prefix)
		out.String(string(in.RTT))
	}
	{
		const prefix string = ",\"overhead\":"
		out.RawString(prefix)
		out.String(string(in.Overhead))
	}
	{
		const prefix string = ",\"dual_mode\":"
		out.RawString(prefix)
		out.String(string(in.DualMode))
	}
	{
		const prefix string = ",\"fwmark_mask\":"
		out.RawString(prefix)
		out.String(string(in.FwmarkMask))
	}
	{
		const prefix string = ",\"nat_enabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.NATEnabled))
	}
	{
		const prefix string = ",\"atm_mode\":"
		out.RawString(prefix)
		out.String(string(in.ATMMode))
	}
	{
		const prefix string = ",\"mpu\":"
		out.RawString(prefix)
		out.String(string(in.MPU))
	}
	{
		const prefix string = ",\"wash_enabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.WashEnabled))
	}
	{
		const prefix string = ",\"memlimit\":"
		out.RawString(prefix)
		out.String(string(in.MemLimit))
	}
	{
		const prefix string = ",\"raw_header\":"
		out.RawString(prefix)
		out.String(string(in.RawHeader))
	}
	{
		const prefix string = ",\"sent_bytes\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.SentBytes))
	}
	{
		const prefix string = ",\"sent_pkts\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.SentPkts))
	}
	{
		const prefix string = ",\"dropped\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Dropped))
	}
	{
		const prefix string = ",\"overlimits\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Overlimits))
	}
	{
		const prefix string = ",\"requeues\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Requeues))
	}
	{
		const prefix string = ",\"backlog_bytes\":"
		out.RawString(prefix)
		out.String(string(in.BacklogBytes))
	}
	{
		const prefix string = ",\"backlog_pkts\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.BacklogPkts))
	}
	{
		const prefix string = ",\"memory_used\":"
		out.RawString(prefix)
		out.String(string(in.MemoryUsed))
	}
	{
		const prefix string = ",\"memory_total\":"
		out.RawString(prefix)
		out.String(string(in.MemoryTotal))
	}
	{
		const prefix string = ",\"capacity_estimate\":"
		out.RawString(prefix)
		out.String(string(in.CapacityEst))
	}
	{
		const prefix string = ",\"min_net_size\":"
		out.RawString(prefix)
		out.String(string(in.MinNetSize))
	}
	{
		const prefix string = ",\"max_net_size\":"
		out.RawString(prefix)
		out.String(string(in.MaxNetSize))
	}
	{
		const prefix string = ",\"min_adj_size\":"
		out.RawString(prefix)
		out.String(string(in.MinAdjSize))
	}
	{
		const prefix string = ",\"max_adj_size\":"
		out.RawString(prefix)
		out.String(string(in.MaxAdjSize))
	}
	{
		const prefix string = ",\"avg_hdr_offset\":"
		out.RawString(prefix)
		out.String(string(in.AvgHdrOffset))
	}
	{
		const prefix string = ",\"tiers\":"
		out.RawString(prefix)
		if in.Tiers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Tiers {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"tx_bytes_per_s\":"
		out.RawString(prefix)
		out.Float64(float64(in.TxBytesPerS))
	}
	{
		const prefix string = ",\"drops_per_s\":"
		out.RawString(prefix)
		out.Float64(float64(in.DropsPerS))
	}
	{
		const prefix string = ",\"max_av_delay_ms\":"
		out.RawString(prefix)
		out.Float64(float64(in.MaxAvDelayMs))
	}
	{
		const prefix string = ",\"max_pk_delay_ms\":"
		out.RawString(prefix)
		out.Float64(float64(in.MaxPkDelayMs))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CakeStats) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGalptCakeStatsPkgTypes3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CakeStats) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGalptCakeStatsPkgTypes3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CakeStats) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGalptCakeStatsPkgTypes3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CakeStats) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGalptCakeStatsPkgTypes3(l, v)
}
